# Changes here will be overwritten by Copier.
_commit: 1.8.6
_src_path: gh:pawamoy/copier-uv
author_email: jean-michel.perraud@csiro.au
author_fullname: J-M
author_username: jmp75
copyright_date: '2025'
copyright_holder: CSIRO
copyright_holder_email: jean-michel.perraud@csiro.au
copyright_license: BSD-3-Clause
insiders: false
project_description: GIS tools for semi-distributed hydrologic modelling
project_name: geosdhydro
python_package_command_line_name: geosdhydro
python_package_distribution_name: geosdhydro
python_package_import_name: geosdhydro
repository_name: geosdhydro
repository_namespace: csiro-hydroinformatics
repository_provider: github.com

